config/routes.rb
Rails.application.routes.draw do
  root 'url#index'
  post 'url/create'
  get 'url/:id' => 'url#show', as: 'url'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
  def ran_string
    ran = ((0...8).map { (65 + rand(26)).chr }.join)
    self.code = ran
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/url_controller.rb
class UrlController < ApplicationController

  def index
    @urls = Url.all
    @url = Url.new
  end

  def create
    @url = Url.new(url_params)

    # create random string
    @url.ran_string
    # some random string... make sure user sees this in my view

    @url.save
    redirect_to root_path
  end

  def show
    @url = Url.find(params[:id])
    redirect_to @url.url
  end



  private

  def url_params
    params.require(:url).permit(:url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/url_helper.rb
module UrlHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Urlshortener</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/url/index.html.erb
<h1> URL Shortener </h1>

<%= form_for @url, url: url_create_path do |f|%>
  <p>
    <%= f.label :Url, "User URL:" %>
    <%= f.text_field :url %>
  </p>
  <p>
      <%= f.submit %>
    </p>

  <% end %>

  <% @urls.each do |a| %>
    <p>
      The URL path for <%= a.url %> is
      <%= link_to(url_path(a), a.url)%>
    </p>
    <p>
      The code for <%= a.url %> is
      <%= link_to(a.ran_string, a.url)%>
    </p>
  <% end %>